language: c

compiler: gcc

sudo: true

addons:
   apt:
      packages:
        - "libcunit1-dev"
        - "kernel-package"
        - "kernel-source"
        - "linux-image-3.13.0-63-generic"
      

script: bash hello_test.sh
