name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make dependency
      run: sudo apt install -y libcunit1-dev linux-headers-$(uname -r) nasm
    - name: make
      run: make
